export const ActionError = {
  FORBIDDEN: "FORBIDDEN",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // Clients
  PHONE_ALREADY_EXISTS: "PHONE_ALREADY_EXISTS",
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  NO_EMAIL_TO_INVITE: "NO_EMAIL_TO_INVITE",
  USER_ROLE_NOT_FOUND: "USER_ROLE_NOT_FOUND",
  LINKED_USER_NOT_FOUND: "LINKED_USER_NOT_FOUND",

  // Products
  SKU_ALREADY_EXISTS: "SKU_ALREADY_EXISTS",
  CANNOT_DELETE_WITH_REFERENCES: "CANNOT_DELETE_WITH_REFERENCES",

  // Users
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_USER_ID: "INVALID_USER_ID",
  CANNOT_DEMOTE_SELF: "CANNOT_DEMOTE_SELF",
  CANNOT_DELETE_SELF: "CANNOT_DELETE_SELF",
  SUPER_ROLE_NOT_FOUND: "SUPER_ROLE_NOT_FOUND",
  CANNOT_DELETE_LAST_SUPER: "CANNOT_DELETE_LAST_SUPER",

  // Permissions
  ACTION_REQUIRED: "ACTION_REQUIRED",

  // Activities
  INVALID_ACTIVITY_ID: "INVALID_ACTIVITY_ID",
  DATE_CANNOT_BE_FUTURE: "DATE_CANNOT_BE_FUTURE",
  ONLY_SUPER_CAN_DELETE: "ONLY_SUPER_CAN_DELETE",

  // Reminders
  INVALID_REMINDER_ID: "INVALID_REMINDER_ID",
  DATE_MUST_BE_FUTURE: "DATE_MUST_BE_FUTURE",

  // Sales
  CANNOT_DELETE_INVOICE: "CANNOT_DELETE_INVOICE",
  INVALID_INVOICE_ID: "INVALID_INVOICE_ID",

  // Import
  NO_FILE_PROVIDED: "NO_FILE_PROVIDED",
  CSV_EMPTY: "CSV_EMPTY",
  MISSING_REQUIRED_COLUMNS: "MISSING_REQUIRED_COLUMNS",
  NO_VALID_ROWS: "NO_VALID_ROWS",

  // Reports
  INVALID_LIMIT: "INVALID_LIMIT",
  INVALID_DAYS: "INVALID_DAYS",
} as const

export type ActionErrorCode =
  (typeof ActionError)[keyof typeof ActionError]
